#!/bin/bash

# Manual deployment script for Mini App
# This script provides step-by-step commands

SERVER_IP="217.198.13.11"
SERVER_USER="root"
DEPLOY_PATH="/var/www/nc-miniapp"
DOMAIN="miniapp.neurosoft.pro"

echo "==================================================="
echo "MINI APP DEPLOYMENT COMMANDS"
echo "==================================================="
echo ""
echo "📋 Step 1: Upload files to server"
echo "---------------------------------------------------"
echo "cd /Users/evgenijkukuskin/Documents/Проекты/cursor/NC_bot"
echo ""
echo "scp -r mini_app root@217.198.13.11:/var/www/nc-miniapp/"
echo "scp -r app root@217.198.13.11:/var/www/nc-miniapp/"
echo "scp Dockerfile.webapp root@217.198.13.11:/var/www/nc-miniapp/"
echo "scp requirements.txt root@217.198.13.11:/var/www/nc-miniapp/"
echo "scp .env root@217.198.13.11:/var/www/nc-miniapp/"
echo "scp deploy/docker-compose.miniapp.yml root@217.198.13.11:/var/www/nc-miniapp/docker-compose.yml"
echo "scp deploy/nginx-miniapp.conf root@217.198.13.11:/tmp/miniapp.conf"
echo ""
echo "📋 Step 2: Connect to server and setup"
echo "---------------------------------------------------"
echo "ssh root@217.198.13.11"
echo ""
echo "# Create directory"
echo "mkdir -p /var/www/nc-miniapp"
echo ""
echo "# Setup Nginx"
echo "mv /tmp/miniapp.conf /etc/nginx/sites-available/miniapp.neurosoft.pro"
echo "ln -sf /etc/nginx/sites-available/miniapp.neurosoft.pro /etc/nginx/sites-enabled/"
echo "nginx -t"
echo "systemctl reload nginx"
echo ""
echo "# Start Docker"
echo "cd /var/www/nc-miniapp"
echo "docker-compose down || true"
echo "docker-compose build"
echo "docker-compose up -d"
echo "docker-compose ps"
echo ""
echo "📋 Step 3: Setup SSL (after DNS is configured)"
echo "---------------------------------------------------"
echo "certbot --nginx -d miniapp.neurosoft.pro --non-interactive --agree-tos --email info@neurosoft.pro"
echo ""
echo "==================================================="
echo "DNS CONFIGURATION"
echo "==================================================="
echo ""
echo "Add the following DNS record to neurosoft.pro:"
echo ""
echo "Type: A"
echo "Name: miniapp"
echo "Value: 217.198.13.11"
echo "TTL: 3600"
echo ""
echo "==================================================="
echo "WEBAPP_URL UPDATE"
echo "==================================================="
echo ""
echo "Update in bot .env file:"
echo "WEBAPP_URL=https://miniapp.neurosoft.pro"
echo ""
echo "==================================================="
